name: Terraform CI

on:
  pull_request:
    branches:
      - master

jobs:
  lint-and-security:
    name: Calidad y Seguridad
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # TFLint (Análisis estático)
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: |
          cd terraform
          tflint

      # Checkov (Análisis de seguridad)
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          framework: terraform
          soft_fail: true

      # Terraform Validate
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

# Generar Plan en formato JSON para OPA (SIN CONEXIÓN A AWS)
      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: mock_access_key
          AWS_SECRET_ACCESS_KEY: mock_secret_key
          AWS_REGION: us-east-1
        run: |
          # Generamos el plan basándonos solo en el código local
          terraform plan -out=tfplan -refresh=false
          
          # Convertimos ese plan a JSON para que OPA pueda leerlo
          terraform show -json tfplan > tfplan.json
        working-directory: ./terraform

      #  Instalar OPA
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      #  Ejecutar evaluación de políticas OPA
      - name: Run OPA Check
        run: |
          opa eval -i terraform/tfplan.json -d opa/policies.rego "data.terraform.policies"
